version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - taskgram-net

  weaver:
    image: ondd/taskgram
    container_name: taskgram
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - taskgram-net
networks:
  taskgram-net:
    external: true