# application.yml (공통 설정)

spring:
  profiles:
    active: local # local || prod(operation) || test(not in use) || LocalTest

  #swagger
  mvc:
    path match:
      matching-strategy: ant_path_matcher
